markdown: redcarpet
name: Frontend Guides
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
include:
- .scss-lint.yml

permalink: pretty
highlighter: rouge

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: CSS coding styleguide
  url: css-coding-styleguide/
  internal: true
  children:
  - text: Preprocessor
    url: preprocessor/
    internal: true
  - text: Frameworks
    url: frameworks/
    internal: true
  - text: Format
    url: format/
    internal: true
  - text: Units
    url: units/
    internal: true
  - text: Naming
    url: naming/
    internal: true
  - text: Inheritance
    url: inheritance/
    internal: true
  - text: Architecture
    url: architecture/
    internal: true
  - text: Specificity
    url: specificity/
    internal: true
  - text: Variables
    url: variables/
    internal: true
  - text: Documentation
    url: documentation/
    internal: true
- text: Recommendations
  url: recommendations/
  internal: true
  children:
  - text: Dependency management
    url: dependency-management/
    internal: true
  - text: Libraries
    url: libraries/
    internal: true
  - text: M**V frameworks
    url: mvv-frameworks/
    internal: true
- text: Web components
  url: web-components/
  internal: true

repos:
- name: Frontend Guides
  description: Main repository
  url: https://github.com/18F/frontend

google_analytics_ua: UA-48605964-19

back_link:
  url: "https://pages.18f.gov/guides/"
  text: Read more 18F Guides

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
