title: 18F Front End Guide

permalink: pretty
highlighter: rouge
markdown: redcarpet

sass:
  style: compressed

exclude:
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - go

include:
  - .scss-lint.yml

google_analytics_ua: UA-48605964-19
